### ISSUE TITLE
В стилях отсутствует дублирование кусков кода

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#14]
В шрифтах есть откровенный некрокод:
https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/sass/global/fonts.scss#L1-L21

так же разные шрифты можно подключать через запятую. А ещё можно весь файл переделает с использованием миксина:
```scss
@mixin font-face($family, $url, $weight: 400) {
  @font-face {
    font-family: $family;
    font-style: normal;
    font-weight: $weight;
    src: url("#{$url}.woff2") format("woff2"), url("#{$url}.woff") format("woff");
    font-display: swap;
  }
}

@include font-face("Montserrat", "../fonts/montserrat");
@include font-face("Montserrat", "../fonts/montserratbold", 700);
```
