### ISSUE TITLE
В шапке нужны ссылки с плавным скролом до соответствующего блока. 

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#8]
Хорошая практика дать пользователю выбор
```css
/* Smooth scrolling IF user doesn't have a preference due to motion sensitivities */
@media screen and (prefers-reduced-motion: no-preference) {
  html {
    scroll-behavior: smooth;
  }
}
```
